module.exports = {
    'en': {
        translation: {
            //POSITIVE_SOUND: `<audio src='soundbank://soundlibrary/ui/gameshow/amzn_ui_sfx_gameshow_positive_response_02'/>`,
            NOTIFICATION_SOUND_1: '<audio src="soundbank://soundlibrary/alarms/beeps_and_bloops/bell_03"/>',
            NOTIFICATION_SOUND_2: '<audio src="soundbank://soundlibrary/alarms/beeps_and_bloops/bell_04"/>',
            //YOU_HAVE_A_NOTIFICATION_MSG: '$t(NOTIFICATION_SOUND_1)$t(NOTIFICATION_SOUND_2) You have a notification', 
            YOU_HAVE_A_NOTIFICATION_MSG: 'You have a notification', 
            YOU_DONT_HAVE_A_NOTIFICATION_MSG: 'You don\'t have a notification',
            HERE_IS_THE_QUESTION_MSG: "Here is the question ",
            HERE_ARE_THE_OPTIONS_MSG: "Here are the options: ",
            OR_MSG: " or ",
            //WELCOME_MSG: 'Welcome, you can say Hello or Help. Which would you like to try?',
            WELCOME_MSG: 'Welcome, you have opened Notification Tester',
            HELLO_MSG: 'Hello World!',
            HELP_MSG: 'You can say hello to me! How can I help?',
            GOODBYE_MSG: 'Goodbye!',
            REFLECTOR_MSG: 'You just triggered {{intent}}',
            FALLBACK_MSG: 'Sorry, I don\'t know about that. Please try again.',
            ERROR_MSG: 'Sorry, there was an error. Please try again.',
            ANSWERS_DONT_MATCH_MSG: 'The letter and answer don\'t match. Let me repeat the question. ',
            ANSWER_REGISTERED_MSG: 'Ok, I have saved your answer.',
            NOTIFICATION_QUESTION_MSG: 'Tagore was born in',
            ANSWER_A_MSG: 'a. The United States of America',
            ANSWER_B_MSG: 'b. India',
            ANSWER_C_MSG: 'c. Europe',
            ANSWER_D_MSG: 'd. England',
            CONJUNCTION_MSG: ' and ',
            TURNING_YO_MSG: ' turning {{count}}',
            ALSO_TODAY_MSG: 'Also celebrating their birthday today are: ',
        }
    },
    'de': {
        translation: {
            NOTIFICATION_SOUND_1: '<audio src="soundbank://soundlibrary/alarms/beeps_and_bloops/bell_03"/>',
            NOTIFICATION_SOUND_2: '<audio src="soundbank://soundlibrary/alarms/beeps_and_bloops/bell_04"/>',
            //YOU_HAVE_A_NOTIFICATION_MSG: '$t(NOTIFICATION_SOUND_1)$t(NOTIFICATION_SOUND_2) Sie haben eine Mitteilung',
            YOU_HAVE_A_NOTIFICATION_MSG: 'Sie haben eine Mitteilung',
            YOU_DONT_HAVE_A_NOTIFICATION_MSG: "Sie haben keine Mitteilung",
            HERE_IS_THE_QUESTION_MSG: "Hier ist die Frage ",
            HERE_ARE_THE_OPTIONS_MSG: "Hier sind die Antwortmöglichkeiten: ",
            OR_MSG: " oder ",
            //WELCOME_MSG: 'Wilkommen, Sie können Hallo oder Hilfe sagen. Welches möchten Sie probieren?',
            WELCOME_MSG: 'Wilkommen, Sie haben Notification Tester geöffnet',
            HELLO_MSG: 'Hallo Welt!',
            HELP_MSG: 'Sie können mir Hallo sagen! Wie kann ich helfen?',
            GOODBYE_MSG: 'Tschüss!',
            REFLECTOR_MSG: 'Sie haben gerade {{intent}} geöffnet',
            FALLBACK_MSG: 'Entschuldigung, ich habe nicht verstanden. Versuchen Sie bitte nochmal.',
            ERROR_MSG: 'Entschuldigung, es gab einen Fehler. Versuchen Sie bitte nochmal.',
            ANSWER_REGISTERED_MSG: 'Ok, I have saved your answer.',
            NOTIFICATION_QUESTION_MSG: 'Tagore was born in',
            ANSWER_A_MSG: ' a. The United States of America',
            ANSWER_B_MSG: ' b. India',
            ANSWER_C_MSG: ' c. Europe',
            ANSWER_D_MSG: ' d. England'
        }
    }
}
